"""empty message

Revision ID: 095f32dc8624
Revises: 35d2230900f3
Create Date: 2024-11-14 15:32:39.175947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '095f32dc8624'
down_revision = '35d2230900f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email_password_hash',
               existing_type=mysql.VARCHAR(length=162),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_password_hash',
               existing_type=mysql.VARCHAR(length=162),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
