"""empty message

Revision ID: 27b2584d3773
Revises: 745c0a203f21
Create Date: 2024-12-05 15:02:26.194324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27b2584d3773'
down_revision = '745c0a203f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('email_password_hash', mysql.VARCHAR(length=162), nullable=False))

    # ### end Alembic commands ###
