"""empty message

Revision ID: 50b599a91ba7
Revises: 80e9d5f5609f
Create Date: 2024-10-29 04:41:01.860518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50b599a91ba7'
down_revision = '80e9d5f5609f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('is_shared')

    # ### end Alembic commands ###
