"""empty message

Revision ID: 745c0a203f21
Revises: 095f32dc8624
Create Date: 2024-12-03 06:55:53.313369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745c0a203f21'
down_revision = '095f32dc8624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_favorite', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('my_favorite')

    # ### end Alembic commands ###
