"""empty message

Revision ID: ef0fc8edbd9e
Revises: 50b599a91ba7
Create Date: 2024-11-14 05:43:29.332400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0fc8edbd9e'
down_revision = '50b599a91ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_password_hash', sa.String(length=162), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
